# Generated by Django 5.2.1 on 2025-07-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='Doctor',
            new_name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='Date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
