# Generated by Django 5.2.1 on 2025-07-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_rename_doctor_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
